/**
 * XiaoYi R1 Live v1.1.0
 * 以现实F1赛历作为R1赛历原型，不把现实车手/车队直接写入萧逸世界
 * 基础赛历：Jolpica F1 API；Session信息：OpenF1（可用时）
 */
(function (window, document) {
  'use strict';
  if (window.EVEXiaoYiR1?.version) return;
  const VERSION='1.1.0';
  const SETTINGS_KEY='eve_xiaoyi_r1_settings_v1';
  const CACHE_KEY='eve_xiaoyi_r1_cache_v1';
  const DEFAULTS={enabled:true,useF1Calendar:true,useOpenF1:true,refreshHours:6,nearRaceDays:7,includeTrackLocation:true,includeRealNames:false,allowAiRaceResult:false,debug:false};
  const KEYWORDS=['r1','赛车','比赛','赛事','赛道','直播','排位','杆位','发车','超车','进站','轮胎','调校','遥测','模拟器','工程师','车队','冠军','训练','赛车服','维修区','复盘','冲刺赛','安全车','红旗','黄旗'];
  let settings=read(SETTINGS_KEY,DEFAULTS);let cache=read(CACHE_KEY,{});let timer=null;let initialized=false;
  function read(k,f){try{const v=JSON.parse(localStorage.getItem(k)||'null');return v&&typeof v==='object'?Object.assign({},f,v):Object.assign({},f)}catch(_){return Object.assign({},f)}}
  function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(_){return false}}
  function clean(v,m=10000){return String(v??'').replace(/\r\n?/g,'\n').trim().slice(0,m)}
  function clone(v){try{return window.structuredClone?window.structuredClone(v):JSON.parse(JSON.stringify(v))}catch(_){return v}}
  function emit(n,d={}){try{window.dispatchEvent(new CustomEvent(n,{detail:d}))}catch(_){}}
  function log(...a){if(settings.debug)console.log('[EVEXiaoYiR1]',...a)}
  function configure(next={}){settings=Object.assign({},DEFAULTS,settings,next||{});['enabled','useF1Calendar','useOpenF1','includeTrackLocation','includeRealNames','allowAiRaceResult','debug'].forEach(k=>settings[k]=Boolean(settings[k]));settings.refreshHours=Math.max(1,Math.min(72,Number(settings.refreshHours)||6));settings.nearRaceDays=Math.max(0,Math.min(21,Number(settings.nearRaceDays)||7));write(SETTINGS_KEY,settings);schedule();emit('eve:xiaoyi-r1-settings-updated',{settings:getSettings()});return getSettings()}
  function getSettings(){return Object.assign({},settings)}
  async function json(url){const c=new AbortController();const t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{headers:{Accept:'application/json'},cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
  function raceFromJolpica(raw){const race=raw?.MRData?.RaceTable?.Races?.[0];if(!race)return null;const sessions=[];for(const [key,label] of [['FirstPractice','Practice 1'],['SecondPractice','Practice 2'],['ThirdPractice','Practice 3'],['SprintQualifying','Sprint Qualifying'],['Sprint','Sprint'],['Qualifying','Qualifying']]){const s=race[key];if(s?.date)sessions.push({name:label,date:s.date,time:s.time||null})}sessions.push({name:'Race',date:race.date,time:race.time||null});return{season:String(race.season||''),round:Number(race.round||0),raceName:clean(race.raceName,160),country:clean(race.Circuit?.Location?.country,100),locality:clean(race.Circuit?.Location?.locality,100),circuitName:clean(race.Circuit?.circuitName,160),circuitId:clean(race.Circuit?.circuitId,100),latitude:Number(race.Circuit?.Location?.lat),longitude:Number(race.Circuit?.Location?.long),date:race.date,time:race.time||null,sessions}}
  async function fetchNextRace(){const data=await json('https://api.jolpi.ca/ergast/f1/current/next.json');return raceFromJolpica(data)}
  async function fetchOpenSessions(year){if(!settings.useOpenF1)return[];try{return await json(`https://api.openf1.org/v1/sessions?year=${encodeURIComponent(year)}`)}catch(error){log('OpenF1不可用，使用基础赛历',error);return[]}}
  function sessionTime(s){const value=s?.date_start||s?.date||'';const t=Date.parse(value);return Number.isFinite(t)?t:Infinity}
  function findRelatedSessions(race,sessions){if(!race||!Array.isArray(sessions))return[];const terms=[race.country,race.locality,race.circuitName].map(x=>clean(x,100).toLowerCase()).filter(Boolean);const raceTime=Date.parse(`${race.date}T${race.time||'00:00:00Z'}`);return sessions.filter(s=>{const hay=[s.country_name,s.location,s.circuit_short_name,s.meeting_name].map(x=>clean(x,160).toLowerCase()).join(' ');const near=Math.abs(sessionTime(s)-raceTime)<6*24*3600*1000;return near&&(terms.some(t=>hay.includes(t))||near)}).sort((a,b)=>sessionTime(a)-sessionTime(b)).map(s=>({name:s.session_name||s.session_type||'Session',type:s.session_type||'',dateStart:s.date_start||null,dateEnd:s.date_end||null,location:s.location||race.locality,country:s.country_name||race.country,meetingKey:s.meeting_key,sessionKey:s.session_key}))}
  async function refresh(options={}){if(!settings.enabled||!settings.useF1Calendar)return getState();const age=cache.updatedAt?Date.now()-Date.parse(cache.updatedAt):Infinity;if(!options.force&&age<settings.refreshHours*3600000&&cache.nextRace)return getState();try{const nextRace=await fetchNextRace();const sessions=nextRace?findRelatedSessions(nextRace,await fetchOpenSessions(nextRace.season||new Date().getFullYear())):[];cache={updatedAt:new Date().toISOString(),nextRace,sessions,error:null};write(CACHE_KEY,cache);emit('eve:xiaoyi-r1-updated',getState());schedule();return getState()}catch(error){cache.error=String(error?.message||error);write(CACHE_KEY,cache);emit('eve:xiaoyi-r1-error',{error:cache.error});schedule();return getState()}}
  function schedule(){if(timer)clearTimeout(timer);timer=null;if(!settings.enabled)return;timer=setTimeout(()=>refresh({force:true}),settings.refreshHours*3600000)}
  function raceDateTime(race){if(!race?.date)return NaN;return Date.parse(`${race.date}T${race.time||'00:00:00Z'}`)}
  function phaseInfo(){const race=cache.nextRace;if(!race)return{phase:'none',days:null};const diff=raceDateTime(race)-Date.now();const days=diff/86400000;if(days>settings.nearRaceDays)return{phase:'future',days};if(days>3)return{phase:'travel-prep',days};if(days>1)return{phase:'race-week',days};if(days>-0.2)return{phase:'race-day',days};if(days>-2)return{phase:'post-race',days};return{phase:'past',days}}
  function currentSession(){const now=Date.now();const sessions=cache.sessions||[];return sessions.find(s=>{const start=Date.parse(s.dateStart),end=Date.parse(s.dateEnd);return Number.isFinite(start)&&Number.isFinite(end)&&now>=start&&now<=end})||null}
  function nextSession(){const now=Date.now();return(cache.sessions||[]).filter(s=>Date.parse(s.dateStart)>now).sort((a,b)=>Date.parse(a.dateStart)-Date.parse(b.dateStart))[0]||null}
  function fmt(iso){if(!iso)return'';try{return new Intl.DateTimeFormat('zh-TW',{month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso))}catch(_){return iso}}
  function shouldExpand(meta={}){const text=`${clean(meta.userText,3000)} ${clean(meta.scene,100)} ${clean(meta.feature,100)}`.toLowerCase();if(KEYWORDS.some(k=>text.includes(k)))return true;const phase=phaseInfo().phase;return['race-week','race-day','post-race'].includes(phase)&&['proactive','momentPost','momentReply'].includes(meta.scene)}
  function getPromptContext(meta={}){if(!settings.enabled)return'';const race=cache.nextRace;const expanded=shouldExpand(meta);const base=['【萧逸的R1职业身份】','萧逸是Glitter Bullet车队的现役R1职业赛车手，也是R1五冠王','R1是世界观中的最高级别国际单座方程式赛事，竞技层级可类比现实F1，但R1并不等同于现实F1','赛车是他的职业、天赋和长期训练成果，不是装饰性标签'];if(!race)return base.join('\n');const phase=phaseInfo();const session=currentSession();const upcoming=nextSession();base.push(`下一站R1赛历原型：第${race.round||'?'}站 ${race.country||''} ${race.circuitName||race.raceName||''}，正赛日期${race.date}`);if(settings.includeTrackLocation&&race.locality)base.push(`比赛地：${race.locality}`);if(session)base.push(`当前比赛周末阶段：${session.name}正在进行`);else if(upcoming)base.push(`下一场赛道活动：${upcoming.name}，时间${fmt(upcoming.dateStart)}`);else base.push(`当前阶段：${phase.phase}`);base.push('现实F1只作为R1赛历、比赛周末流程与赛道环境原型；不要主动说出现实车手或车队名称');base.push('现实比赛结果不会自动等于萧逸的成绩。除非剧情已经确定，否则不要擅自宣布萧逸夺冠、退赛、受伤或具体名次');if(expanded){base.push('涉及赛车时，应表现出五冠王应有的比赛阅读、车辆反馈、轮胎管理、进站窗口、调校、遥测和车队协作能力，但不要为了证明专业而堆砌术语');base.push('胜利时自信但不浮夸，失利时先复盘并准备下一场，不把压力全部倾倒给夕月');}return base.join('\n')}
  function getState(){return{version:VERSION,settings:getSettings(),cache:clone(cache),phase:phaseInfo(),currentSession:clone(currentSession()),nextSession:clone(nextSession())}}
  function openSettings(){document.getElementById('eve-r1-settings-modal')?.remove();const overlay=document.createElement('div');overlay.id='eve-r1-settings-modal';overlay.style.cssText='position:fixed;inset:0;z-index:1000001;background:#0008;display:flex;align-items:center;justify-content:center;padding:12px';const state=getState();overlay.innerHTML=`<div style="width:min(560px,100%);max-height:90vh;overflow:auto;background:var(--secondary-bg,#fff);color:var(--text-primary,#222);border-radius:18px"><div style="display:flex;padding:15px;border-bottom:1px solid #ddd"><b style="flex:1">R1实时赛事</b><button data-close>✕</button></div><div style="padding:14px;line-height:1.7"><label><input id="r1-enabled" type="checkbox" ${settings.enabled?'checked':''}> 启用R1实时赛事</label><br><label><input id="r1-openf1" type="checkbox" ${settings.useOpenF1?'checked':''}> 使用OpenF1补充Session信息</label><br><label><input id="r1-location" type="checkbox" ${settings.includeTrackLocation?'checked':''}> 提供比赛地点</label><br><label><input id="r1-results" type="checkbox" ${settings.allowAiRaceResult?'checked':''}> 允许AI自行生成萧逸比赛结果（不建议）</label><div style="margin-top:10px">刷新间隔（小时）<input id="r1-hours" type="number" min="1" max="72" value="${settings.refreshHours}" style="width:70px"></div><pre style="white-space:pre-wrap;background:#0000000d;padding:10px;border-radius:10px">${clean(JSON.stringify({nextRace:state.cache.nextRace,phase:state.phase,currentSession:state.currentSession,nextSession:state.nextSession},null,2),5000)}</pre><div style="display:flex;gap:8px;justify-content:flex-end"><button data-refresh>立即刷新</button><button data-save style="background:#4a84c1;color:#fff;border:0;padding:8px 12px;border-radius:9px">保存</button></div></div></div>`;document.body.appendChild(overlay);overlay.querySelector('[data-close]').onclick=()=>overlay.remove();overlay.onclick=e=>{if(e.target===overlay)overlay.remove()};overlay.querySelector('[data-save]').onclick=()=>{configure({enabled:overlay.querySelector('#r1-enabled').checked,useOpenF1:overlay.querySelector('#r1-openf1').checked,includeTrackLocation:overlay.querySelector('#r1-location').checked,allowAiRaceResult:overlay.querySelector('#r1-results').checked,refreshHours:Number(overlay.querySelector('#r1-hours').value)||6});overlay.remove()};overlay.querySelector('[data-refresh]').onclick=async()=>{await refresh({force:true});overlay.remove();openSettings()}}
  function init(){if(initialized)return Promise.resolve(getState());initialized=true;schedule();refresh().catch(()=>{});emit('eve:xiaoyi-r1-ready',getState());return Promise.resolve(getState())}
  function destroy(){if(timer)clearTimeout(timer);timer=null;initialized=false}
  window.EVEXiaoYiR1=Object.freeze({version:VERSION,init,destroy,configure,getSettings,getState,refresh,getPromptContext,openSettings,keywords:KEYWORDS.slice()});
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})(window,document);
